# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_bp_swift4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_bp_swift4
  pod 'Alamofire'
  target 'ios_bp_swift4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_bp_swift4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
